#ifndef SERVO_REPEATABILITY_CONFIG_H
#define SERVO_REPEATABILITY_CONFIG_H

#define SERVO_MODE_UNCONFIRMED 0
#define SERVO_MODE_POSITIONAL 1
#define SERVO_MODE_CONTINUOUS 2

// Identify the physical servo, then override this to exactly one configured mode.
#ifndef SERVO_REPEATABILITY_MODE
#define SERVO_REPEATABILITY_MODE SERVO_MODE_UNCONFIRMED
#endif

#ifndef SERVO_REPEATABILITY_MIN_US
#define SERVO_REPEATABILITY_MIN_US 1400
#endif
#ifndef SERVO_REPEATABILITY_MAX_US
#define SERVO_REPEATABILITY_MAX_US 1600
#endif
#ifndef SERVO_REPEATABILITY_LOW_US
#define SERVO_REPEATABILITY_LOW_US 1450
#endif
#ifndef SERVO_REPEATABILITY_TARGET_US
#define SERVO_REPEATABILITY_TARGET_US 1500
#endif
#ifndef SERVO_REPEATABILITY_STOP_US
#define SERVO_REPEATABILITY_STOP_US 1500
#endif
#ifndef SERVO_REPEATABILITY_HIGH_US
#define SERVO_REPEATABILITY_HIGH_US 1550
#endif
#ifndef SERVO_REPEATABILITY_SETTLE_MS
#define SERVO_REPEATABILITY_SETTLE_MS 1000UL
#endif
#ifndef SERVO_REPEATABILITY_MOTION_MS
#define SERVO_REPEATABILITY_MOTION_MS 500UL
#endif
#ifndef SERVO_REPEATABILITY_REPETITIONS
#define SERVO_REPEATABILITY_REPETITIONS 2
#endif

#endif
